export const ERROR_CODES = {
  // Auth
  UNAUTHORIZED: "UNAUTHORIZED",
  FORBIDDEN: "FORBIDDEN",
  VALIDATION_ERROR: "VALIDATION_ERROR",
   AUTH_EXPIRED_TOKEN: "AUTH_EXPIRED_TOKEN",

  // Business
  BID_ALREADY_ACCEPTED: "BID_ALREADY_ACCEPTED",
  LISTING_CLOSED: "LISTING_CLOSED",
  CONTRACT_NOT_COMPLETED: "CONTRACT_NOT_COMPLETED",
  PAYMENT_ALREADY_DONE: "PAYMENT_ALREADY_DONE",
  INVALID_STATUS_TRANSITION: "INVALID_STATUS_TRANSITION",
  LISTING_ALREADY_CONTRACTED: "LISTING_ALREADY_CONTRACTED",
  PAYMENT_ALREADY_MARKED: "PAYMENT_ALREADY_MARKED",

  // Generic
  NOT_FOUND: "NOT_FOUND",
  CONFLICT: "CONFLICT",
  INTERNAL_ERROR: "INTERNAL_ERROR",
  
  // Permission
  PERMISSION_DENIED: "PERMISSION_DENIED",

  // Validation
  VALIDATION_FAILED: "VALIDATION_FAILED",

  // Resource
  RESOURCE_NOT_FOUND: "RESOURCE_NOT_FOUND",
  

  // Rate limit
  RATE_LIMIT_EXCEEDED: "RATE_LIMIT_EXCEEDED",


};
